package com.example.ai

import android.graphics.Bitmap
import android.util.Base64
import com.example.BuildConfig
import com.example.data.model.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import kotlin.math.abs
import kotlin.math.sqrt

class GeminiNavService {

    /**
     * Phase 11: Grounded Navigation Assistant Core
     * Grounded strictly in real application context, building data, location, and route.
     * Prevents hallucination of rooms, floors, routes, or distances.
     */
    suspend fun processNavigationQuery(
        userQuery: String,
        context: AINavigationContext,
        building: Building
    ): AIAssistantResponse = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY.trim()
        val hasValidKey = apiKey.isNotEmpty() && apiKey != "MY_GEMINI_API_KEY"

        if (hasValidKey) {
            try {
                val nodesSummary = building.nodes.map { node ->
                    mapOf(
                        "id" to node.id,
                        "name" to node.name,
                        "code" to node.code,
                        "floor" to node.floor,
                        "category" to node.category.name,
                        "isAccessible" to node.isAccessible,
                        "isEmergencyExit" to (node.isEmergencyExit || node.category == NodeCategory.EMERGENCY),
                        "description" to node.description,
                        "keywords" to node.keywords
                    )
                }

                val prompt = buildString {
                    appendLine("You are the grounded AI Navigation Assistant for PathFinder AI inside \"${context.buildingName}\".")
                    appendLine("Your mission is to provide accurate, grounded, helpful guidance to people navigating inside this building.")
                    appendLine()
                    appendLine("ABSOLUTE GROUNDING & SAFETY RULES (HALLUCINATION PREVENTION):")
                    appendLine("1. Use ONLY the supplied APPLICATION CONTEXT and PUBLISHED BUILDING NODES below.")
                    appendLine("2. NEVER INVENT rooms, buildings, floors, routes, distances, ETA, elevator availability, emergency exits, or accessibility features.")
                    appendLine("3. NEVER CALCULATE OR FABRICATE ALTERNATIVE ROUTES. Route calculations are authoritatively generated by the application's A* routing engine.")
                    appendLine("4. \"Where am I?\":")
                    appendLine("   - If location confidence is \"UNCERTAIN\" or isLocationUncertain is true: Respond: \"Your current location is uncertain. Please scan a QR calibration point or move closer to a BLE-enabled area.\"")
                    appendLine("   - Otherwise, state the exact known location: \"You are near ${context.currentNodeName ?: "Unknown location"} on Floor ${context.currentFloor} of ${context.buildingName}.\"")
                    appendLine("5. \"Where is [X]?\" / \"Which floor is [X] on?\":")
                    appendLine("   - Search the published building nodes.")
                    appendLine("   - If found: State its name, code, and floor (e.g., \"AI Laboratory is on Floor 2 of Engineering Block.\").")
                    appendLine("   - If multiple match: Mention the possibilities so the user can choose.")
                    appendLine("   - If not found: State clearly: \"I couldn't find [X] in the currently available building data.\"")
                    appendLine("6. \"How do I get there?\" / \"How do I get to [X]?\":")
                    appendLine("   - If an active route exists: Summarize the actual route steps provided in the context.")
                    appendLine("   - If no route exists: State the destination location and floor, and suggest starting navigation.")
                    appendLine("7. \"What should I do next?\":")
                    appendLine("   - If navigating: State the current route step instruction and distance: e.g. \"${context.currentRouteStepInstruction ?: "Continue along the path"} in about ${context.distanceToNextActionMeters?.toInt() ?: 10} meters.\"")
                    appendLine("   - If not navigating: \"Start navigation to a destination and I can guide you step by step.\"")
                    appendLine("8. \"How far?\" / \"How long?\":")
                    appendLine("   - Use the authoritative remaining distance (${context.remainingDistanceMeters?.toInt() ?: 0}m) and ETA (${context.estimatedMinutes ?: 0} min). NEVER guess or change this number.")
                    appendLine("9. \"Can I reach it using a wheelchair?\" / \"Is there an accessible route?\":")
                    appendLine("   - Refer to wheelchairAccessibleMode and isRouteAccessible. If no accessible route exists, state clearly: \"No wheelchair-accessible route is currently available in the published building graph.\"")
                    appendLine("10. \"Where is the nearest [restroom / elevator / emergency exit / cafeteria / etc.]?\":")
                    appendLine("    - Refer only to published nodes matching that category. If emergency exit, treat with high priority.")
                    appendLine("11. Keep spoken/voice response concise (1 short sentence) suitable for a walking user.")
                    appendLine()
                    appendLine("APPLICATION CONTEXT:")
                    appendLine("- Current Building: ${context.buildingName} (ID: ${context.buildingId})")
                    appendLine("- Current Floor: Floor ${context.currentFloor}")
                    appendLine("- Current Location: ${context.currentNodeName ?: "Uncertain"} (${context.currentNodeCode ?: ""})")
                    appendLine("- Coordinates: (${context.currentX ?: 0f}, ${context.currentY ?: 0f})")
                    appendLine("- Location Confidence: ${context.locationConfidence} (Uncertain: ${context.isLocationUncertain})")
                    appendLine("- Navigation State: ${context.navigationState.name} (Navigating: ${context.isNavigating})")
                    appendLine("- Destination: ${context.destinationName ?: "None"} (Floor ${context.destinationFloor ?: -1})")
                    appendLine("- Current Route Step: ${context.currentRouteStepInstruction ?: "None"}")
                    appendLine("- Distance to Next Action: ${context.distanceToNextActionMeters ?: 0f} meters")
                    appendLine("- Remaining Total Distance: ${context.remainingDistanceMeters ?: 0f} meters")
                    appendLine("- Estimated Walking Time: ${context.estimatedMinutes ?: 0} minutes")
                    appendLine("- Floor Transfers on Route: ${context.floorTransfers.joinToString("; ").ifEmpty { "None" }}")
                    appendLine("- Wheelchair Mode: ${if (context.isWheelchairMode) "Enabled" else "Disabled"}")
                    appendLine("- Route Accessible: ${context.isRouteAccessible}")
                    appendLine()
                    appendLine("PUBLISHED BUILDING NODES:")
                    appendLine(JSONArray(nodesSummary).toString(2))
                    appendLine()
                    appendLine("USER QUERY: \"$userQuery\"")
                    appendLine()
                    appendLine("Respond ONLY with a JSON object in this exact schema:")
                    appendLine("{")
                    appendLine("  \"intent\": \"NAVIGATE_TO | SEARCH_LOCATION | CURRENT_LOCATION | NEXT_INSTRUCTION | ROUTE_SUMMARY | ACCESSIBILITY | NEAREST_LOCATION | BUILDING_INFORMATION | FLOOR_INFORMATION | EMERGENCY | UNKNOWN\",")
                    appendLine("  \"targetQuery\": \"extracted search phrase or destination or null\",")
                    appendLine("  \"textResponse\": \"Grounded detailed answer to user query\",")
                    appendLine("  \"suggestedVoiceResponse\": \"Concise spoken answer (max 1 sentence)\",")
                    appendLine("  \"action\": \"START_NAVIGATION | VIEW_ROUTE | RECALCULATE | SHOW_NEAREST | CANCEL_ROUTE | SCAN_QR | NONE\",")
                    appendLine("  \"resolvedNodeId\": \"exact_node_id_or_null\",")
                    appendLine("  \"isEmergency\": false")
                    appendLine("}")
                }

                val request = GeminiRequest(
                    contents = listOf(
                        GeminiContent(
                            parts = listOf(GeminiPart(text = prompt))
                        )
                    ),
                    generationConfig = GeminiGenerationConfig(
                        temperature = 0.2f,
                        responseMimeType = "application/json"
                    )
                )

                val response = GeminiClient.service.generateContent(apiKey, request)
                val responseText = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text

                if (!responseText.isNullOrBlank()) {
                    val parsed = parseAssistantResponseJson(responseText, building, context)
                    if (parsed != null) return@withContext parsed
                }
            } catch (e: Exception) {
                // Fall through to deterministic local engine on network or API failure
            }
        }

        // 100% Deterministic Local Grounded Assistant Engine
        return@withContext deterministicLocalAssistantEngine(userQuery, context, building)
    }

    /**
     * Backward-compatible intent resolver for Phase 2-9 callers.
     */
    suspend fun resolveUserIntent(
        userQuery: String,
        building: Building
    ): AIIntentResult = withContext(Dispatchers.IO) {
        val dummyContext = AINavigationContext(
            buildingId = building.id,
            buildingName = building.name,
            currentFloor = building.floors.firstOrNull()?.floorNumber ?: 1
        )
        val assistantResponse = processNavigationQuery(userQuery, dummyContext, building)
        val targetNodeId = assistantResponse.resolvedTargetNode?.id 
            ?: assistantResponse.multipleMatches.firstOrNull()?.id 
            ?: building.nodes.firstOrNull()?.id
        AIIntentResult(
            targetNodeId = targetNodeId,
            confidence = assistantResponse.confidence,
            explanation = assistantResponse.textResponse,
            suggestedVoiceResponse = assistantResponse.suggestedVoiceResponse
        )
    }

    /**
     * Internal LLM Prompt 2B: Gemini Vision Camera Landmark Identification Prompt
     */
    suspend fun identifyLandmark(
        bitmap: Bitmap,
        building: Building
    ): AILandmarkResult = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY.trim()

        val nodesListSummary = building.nodes.map { node ->
            mapOf(
                "id" to node.id,
                "name" to node.name,
                "code" to node.code,
                "floor" to "Level ${node.floor}",
                "signageHint" to node.visualSignageHint,
                "description" to node.description
            )
        }
        val nodesJsonString = JSONArray(nodesListSummary).toString(2)

        val prompt = """
Analyze this indoor building photo (signboard, room door, wall plaque, kiosk, or entrance) taken inside "${building.name}".
Find which location from this list matches the image:
${nodesJsonString}

Return ONLY a JSON object in this exact format:
{
  "matchedNodeId": "exact_node_id_or_null",
  "landmarkName": "Identified text or visual landmark",
  "confidence": 0.92,
  "explanation": "Found room name or sign in the image."
}
        """.trimIndent()

        if (apiKey.isNotEmpty() && apiKey != "MY_GEMINI_API_KEY") {
            try {
                val base64Image = bitmapToBase64(bitmap)
                val request = GeminiRequest(
                    contents = listOf(
                        GeminiContent(
                            parts = listOf(
                                GeminiPart(text = prompt),
                                GeminiPart(inlineData = GeminiInlineData(mimeType = "image/jpeg", data = base64Image))
                            )
                        )
                    ),
                    generationConfig = GeminiGenerationConfig(
                        temperature = 0.2f,
                        responseMimeType = "application/json"
                    )
                )

                val response = GeminiClient.service.generateContent(apiKey, request)
                val responseText = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text

                if (!responseText.isNullOrBlank()) {
                    val parsed = parseLandmarkJson(responseText, building)
                    if (parsed != null) return@withContext parsed
                }
            } catch (e: Exception) {
                // Fallback to local landmark scanner heuristic
            }
        }

        // Local heuristic fallback for landmark calibration
        return@withContext localFallbackLandmarkMatch(building)
    }

    private fun parseAssistantResponseJson(
        jsonStr: String,
        building: Building,
        context: AINavigationContext
    ): AIAssistantResponse? {
        return try {
            val clean = jsonStr.replace("```json", "").replace("```", "").trim()
            val obj = JSONObject(clean)

            val intentStr = obj.optString("intent", "UNKNOWN")
            val intent = try {
                AINavigationIntent.valueOf(intentStr.uppercase())
            } catch (e: Exception) {
                AINavigationIntent.UNKNOWN
            }

            val textResponse = obj.optString("textResponse", "I am ready to help you navigate.")
            val suggestedVoice = obj.optString("suggestedVoiceResponse", textResponse.take(80))
            val actionStr = obj.optString("action", "NONE")
            val action = try {
                AIAssistantAction.valueOf(actionStr.uppercase())
            } catch (e: Exception) {
                AIAssistantAction.NONE
            }

            val resolvedNodeId = obj.optString("resolvedNodeId", "")
            // Strict grounding check: Node MUST exist in the authoritative building database
            val resolvedNode = building.nodes.firstOrNull { it.id == resolvedNodeId }

            val targetQuery = obj.optString("targetQuery", "")
            val multipleMatches = if (resolvedNode == null && targetQuery.isNotBlank()) {
                building.nodes.filter {
                    it.name.contains(targetQuery, ignoreCase = true) ||
                            it.code.contains(targetQuery, ignoreCase = true)
                }
            } else emptyList()

            val isEmergency = obj.optBoolean("isEmergency", false) || intent == AINavigationIntent.EMERGENCY

            AIAssistantResponse(
                intent = intent,
                textResponse = textResponse,
                suggestedVoiceResponse = suggestedVoice,
                action = action,
                resolvedTargetNode = resolvedNode ?: multipleMatches.firstOrNull(),
                multipleMatches = if (multipleMatches.size > 1) multipleMatches else emptyList(),
                isEmergency = isEmergency,
                confidence = 0.95f
            )
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Resilient, 100% Deterministic Local Assistant Engine
     * Used when offline, during network timeouts, or when API key is not configured.
     * Guarantees that the assistant NEVER crashes, NEVER invents fake nodes, and ALWAYS grounds answers.
     */
    private fun deterministicLocalAssistantEngine(
        userQuery: String,
        context: AINavigationContext,
        building: Building
    ): AIAssistantResponse {
        val q = userQuery.lowercase().trim()

        // 1. EMERGENCY INTENT
        val isEmergencyQuery = q.contains("emergency") || q.contains("fire") ||
                q.contains("evacuate") || q.contains("danger") || q.contains("hazard") ||
                q.contains("fire exit") || (q.contains("help") && (q.contains("need") || q.contains("urgent")))

        if (isEmergencyQuery) {
            val (nearestExit, exitDist) = findNearestNode(building, context) {
                it.isEmergencyExit || it.category == NodeCategory.EMERGENCY || it.id.contains("exit")
            }

            return if (nearestExit != null) {
                AIAssistantResponse(
                    intent = AINavigationIntent.EMERGENCY,
                    textResponse = "Emergency exit identified: ${nearestExit.name} (${nearestExit.code}) on Floor ${nearestExit.floor}, approximately ${exitDist.toInt()}m away. Proceed to the exit immediately.",
                    suggestedVoiceResponse = "Head immediately to ${nearestExit.name} on Floor ${nearestExit.floor}.",
                    action = AIAssistantAction.START_NAVIGATION,
                    resolvedTargetNode = nearestExit,
                    isEmergency = true,
                    confidence = 0.99f
                )
            } else {
                val fallbackExit = building.nodes.firstOrNull { it.category == NodeCategory.ENTRANCE }
                AIAssistantResponse(
                    intent = AINavigationIntent.EMERGENCY,
                    textResponse = "Please proceed to the main entrance on Floor 1 immediately.",
                    suggestedVoiceResponse = "Proceed to the main entrance immediately.",
                    action = if (fallbackExit != null) AIAssistantAction.START_NAVIGATION else AIAssistantAction.NONE,
                    resolvedTargetNode = fallbackExit,
                    isEmergency = true,
                    confidence = 0.9f
                )
            }
        }

        // 2. "WHERE AM I?" / CURRENT LOCATION INTENT
        if (q.contains("where am i") || q.contains("my location") || q.contains("current location") ||
            q.contains("where are we") || q.contains("current position") || q == "where am i?") {

            if (context.isLocationUncertain || context.locationConfidence == "UNCERTAIN" || context.currentNodeName == null) {
                return AIAssistantResponse(
                    intent = AINavigationIntent.CURRENT_LOCATION,
                    textResponse = "Your current location is uncertain. Please scan a QR calibration point or move closer to a BLE-enabled area.",
                    suggestedVoiceResponse = "Your location is uncertain. Please scan a QR calibration point.",
                    action = AIAssistantAction.SCAN_QR,
                    confidence = 0.5f
                )
            } else {
                return AIAssistantResponse(
                    intent = AINavigationIntent.CURRENT_LOCATION,
                    textResponse = "You are near ${context.currentNodeName} (${context.currentNodeCode ?: ""}) on Floor ${context.currentFloor} of ${context.buildingName}.",
                    suggestedVoiceResponse = "You are near ${context.currentNodeName} on Floor ${context.currentFloor}.",
                    confidence = 0.95f
                )
            }
        }

        // 3. "WHAT SHOULD I DO NEXT?" / NEXT INSTRUCTION INTENT
        if (q.contains("what should i do next") || q.contains("what next") ||
            q.contains("next instruction") || q.contains("next step") ||
            q.contains("which way") || q.contains("where do i go") || q == "next") {

            if (context.isNavigating && context.currentRouteStepInstruction != null) {
                val dist = context.distanceToNextActionMeters?.toInt() ?: 10
                val instructionText = if (dist <= 3) {
                    "${context.currentRouteStepInstruction} now."
                } else {
                    "${context.currentRouteStepInstruction} in about $dist meters."
                }

                return AIAssistantResponse(
                    intent = AINavigationIntent.NEXT_INSTRUCTION,
                    textResponse = instructionText,
                    suggestedVoiceResponse = instructionText,
                    action = AIAssistantAction.NONE,
                    confidence = 0.98f
                )
            } else if (context.navigationState == NavSessionState.FLOOR_TRANSITION) {
                return AIAssistantResponse(
                    intent = AINavigationIntent.NEXT_INSTRUCTION,
                    textResponse = "Please proceed to your floor transition via the elevator or stairs to reach Floor ${context.destinationFloor ?: context.currentFloor}.",
                    suggestedVoiceResponse = "Take the elevator or stairs to change floors.",
                    action = AIAssistantAction.NONE,
                    confidence = 0.95f
                )
            } else {
                return AIAssistantResponse(
                    intent = AINavigationIntent.NEXT_INSTRUCTION,
                    textResponse = "Start navigation to a destination and I can guide you step by step.",
                    suggestedVoiceResponse = "Select a destination to start step by step guidance.",
                    action = AIAssistantAction.NONE,
                    confidence = 0.9f
                )
            }
        }

        // 4. "HOW FAR?" / "HOW LONG?" / DISTANCE & ETA INTENT
        if (q.contains("how far") || q.contains("how long") || q.contains("eta") ||
            q.contains("remaining distance") || q.contains("how much time") || q.contains("how many meters")) {

            if (context.remainingDistanceMeters != null && context.remainingDistanceMeters > 0) {
                val dist = context.remainingDistanceMeters.toInt()
                val minutes = context.estimatedMinutes ?: 1
                val dest = context.destinationName ?: "destination"

                return AIAssistantResponse(
                    intent = AINavigationIntent.ROUTE_SUMMARY,
                    textResponse = "Your destination ($dest) is approximately $dist meters away, about $minutes minute(s) on foot.",
                    suggestedVoiceResponse = "Your destination is $dist meters away, about $minutes minutes on foot.",
                    action = AIAssistantAction.NONE,
                    confidence = 0.99f
                )
            } else {
                return AIAssistantResponse(
                    intent = AINavigationIntent.ROUTE_SUMMARY,
                    textResponse = "You do not have an active navigation route. Please select a destination to see the distance and walking time.",
                    suggestedVoiceResponse = "Select a destination to see the remaining distance.",
                    action = AIAssistantAction.NONE,
                    confidence = 0.9f
                )
            }
        }

        // 5. ACCESSIBILITY INTENT
        if (q.contains("wheelchair") || q.contains("accessible") || q.contains("without stairs") ||
            q.contains("avoid stairs") || q.contains("step-free") || q.contains("ramp")) {

            if (context.isNavigating) {
                return if (context.isRouteAccessible) {
                    AIAssistantResponse(
                        intent = AINavigationIntent.ACCESSIBILITY,
                        textResponse = "Yes. The current accessible route uses the elevator and avoids stairs.",
                        suggestedVoiceResponse = "Yes, the current route avoids stairs and uses the elevator.",
                        action = AIAssistantAction.NONE,
                        confidence = 0.98f
                    )
                } else {
                    AIAssistantResponse(
                        intent = AINavigationIntent.ACCESSIBILITY,
                        textResponse = "No wheelchair-accessible route is currently available in the published building graph.",
                        suggestedVoiceResponse = "No wheelchair accessible route is currently available.",
                        action = AIAssistantAction.NONE,
                        confidence = 0.95f
                    )
                }
            } else {
                val modeDesc = if (context.isWheelchairMode) "currently ENABLED" else "disabled"
                return AIAssistantResponse(
                    intent = AINavigationIntent.ACCESSIBILITY,
                    textResponse = "Wheelchair Accessible mode is $modeDesc. When enabled, PathFinder AI prioritizes elevators, ramps, and wide doors while avoiding stairs.",
                    suggestedVoiceResponse = "Accessible routing is $modeDesc.",
                    action = AIAssistantAction.NONE,
                    confidence = 0.9f
                )
            }
        }

        // 6. NEAREST LOCATION QUERIES (Restroom, Elevator, Cafeteria, Pharmacy, Reception, Stairs)
        if (q.contains("nearest") || q.contains("closest")) {
            val (category, label) = when {
                q.contains("restroom") || q.contains("toilet") || q.contains("washroom") || q.contains("bathroom") || q.contains("wc") ->
                    Pair(NodeCategory.RESTROOM, "restroom")
                q.contains("elevator") || q.contains("lift") ->
                    Pair(NodeCategory.ELEVATOR, "elevator")
                q.contains("stair") ->
                    Pair(NodeCategory.STAIRS, "stairs")
                q.contains("cafe") || q.contains("food") || q.contains("canteen") || q.contains("eat") || q.contains("coffee") ->
                    Pair(NodeCategory.FOOD_COURT, "cafeteria")
                q.contains("pharmacy") || q.contains("medicine") || q.contains("drug") ->
                    Pair(NodeCategory.PHARMACY, "pharmacy")
                q.contains("reception") || q.contains("help") || q.contains("info") || q.contains("desk") ->
                    Pair(NodeCategory.RECEPTION, "reception")
                q.contains("exit") ->
                    Pair(NodeCategory.EMERGENCY, "exit")
                else -> Pair(null, "facility")
            }

            if (category != null) {
                val (nearestNode, dist) = findNearestNode(building, context) { it.category == category }
                if (nearestNode != null) {
                    return AIAssistantResponse(
                        intent = AINavigationIntent.NEAREST_LOCATION,
                        textResponse = "The nearest $label is ${nearestNode.name} (${nearestNode.code}) on Floor ${nearestNode.floor}, approximately ${dist.toInt()}m away.",
                        suggestedVoiceResponse = "The nearest $label is ${nearestNode.name} on Floor ${nearestNode.floor}.",
                        action = AIAssistantAction.START_NAVIGATION,
                        resolvedTargetNode = nearestNode,
                        confidence = 0.95f
                    )
                } else {
                    return AIAssistantResponse(
                        intent = AINavigationIntent.NEAREST_LOCATION,
                        textResponse = "No $label was found in the published building data for ${context.buildingName}.",
                        suggestedVoiceResponse = "No $label was found in this building.",
                        action = AIAssistantAction.NONE,
                        confidence = 0.9f
                    )
                }
            }
        }

        // 7. "WHICH FLOOR IS [X] ON?" / FLOOR INFORMATION INTENT
        if (q.contains("which floor") || q.contains("what floor") || q.contains("what level") || q.contains("which level")) {
            val candidate = findMatchingNodes(building, q)
            if (candidate.isNotEmpty()) {
                val best = candidate.first()
                return AIAssistantResponse(
                    intent = AINavigationIntent.FLOOR_INFORMATION,
                    textResponse = "${best.name} (${best.code}) is on Floor ${best.floor} of ${context.buildingName}.",
                    suggestedVoiceResponse = "${best.name} is on Floor ${best.floor}.",
                    action = AIAssistantAction.START_NAVIGATION,
                    resolvedTargetNode = best,
                    confidence = 0.95f
                )
            } else {
                return AIAssistantResponse(
                    intent = AINavigationIntent.FLOOR_INFORMATION,
                    textResponse = "I couldn't find that location in the currently available building data for ${context.buildingName}.",
                    suggestedVoiceResponse = "I couldn't find that location in the building data.",
                    action = AIAssistantAction.NONE,
                    confidence = 0.85f
                )
            }
        }

        // 8. "HOW DO I GET TO [X]?" / ROUTE INQUIRY INTENT
        if (q.contains("how do i get") || q.contains("how to reach") || q.contains("directions to") || q.contains("route to")) {
            if (context.isNavigating && (q.contains("there") || q.contains("destination"))) {
                return AIAssistantResponse(
                    intent = AINavigationIntent.ROUTE_SUMMARY,
                    textResponse = "Continue following the active indoor route to ${context.destinationName}. Current step: ${context.currentRouteStepInstruction ?: "proceed along the corridor"}.",
                    suggestedVoiceResponse = "Follow the active route to ${context.destinationName}.",
                    action = AIAssistantAction.NONE,
                    confidence = 0.95f
                )
            }

            val matching = findMatchingNodes(building, q)
            if (matching.size == 1) {
                val node = matching.first()
                return AIAssistantResponse(
                    intent = AINavigationIntent.NAVIGATE_TO,
                    textResponse = "${node.name} is on Floor ${node.floor}. Would you like to start indoor navigation?",
                    suggestedVoiceResponse = "Found ${node.name} on Floor ${node.floor}. Would you like directions?",
                    action = AIAssistantAction.START_NAVIGATION,
                    resolvedTargetNode = node,
                    confidence = 0.95f
                )
            } else if (matching.size > 1) {
                return AIAssistantResponse(
                    intent = AINavigationIntent.SEARCH_LOCATION,
                    textResponse = "I found multiple matching locations: ${matching.joinToString { "${it.name} (Floor ${it.floor})" }}. Which one would you like?",
                    suggestedVoiceResponse = "I found multiple matching locations. Please select one.",
                    action = AIAssistantAction.VIEW_ROUTE,
                    multipleMatches = matching,
                    confidence = 0.9f
                )
            } else {
                return AIAssistantResponse(
                    intent = AINavigationIntent.SEARCH_LOCATION,
                    textResponse = "I couldn't find that destination in the currently available building data for ${context.buildingName}.",
                    suggestedVoiceResponse = "I couldn't find that destination in this building.",
                    action = AIAssistantAction.NONE,
                    confidence = 0.85f
                )
            }
        }

        // 9. GENERAL NAVIGATION / SEARCH INTENT ("Take me to AI lab", "Library", etc.)
        val candidates = findMatchingNodes(building, q)
        if (candidates.size == 1) {
            val node = candidates.first()
            return AIAssistantResponse(
                intent = AINavigationIntent.NAVIGATE_TO,
                textResponse = "${node.name} (${node.code}) is on Floor ${node.floor}. Ready to calculate A* indoor route.",
                suggestedVoiceResponse = "Navigating you to ${node.name} on Floor ${node.floor}.",
                action = AIAssistantAction.START_NAVIGATION,
                resolvedTargetNode = node,
                confidence = 0.95f
            )
        } else if (candidates.size > 1) {
            return AIAssistantResponse(
                intent = AINavigationIntent.SEARCH_LOCATION,
                textResponse = "I found multiple matching locations: ${candidates.joinToString { "${it.name} (Floor ${it.floor})" }}. Which one would you like to visit?",
                suggestedVoiceResponse = "I found several matches. Please choose your destination.",
                action = AIAssistantAction.VIEW_ROUTE,
                multipleMatches = candidates,
                confidence = 0.9f
            )
        }

        // 10. UNKNOWN / SAFE NO-HALLUCINATION FALLBACK
        return AIAssistantResponse(
            intent = AINavigationIntent.UNKNOWN,
            textResponse = "I don't have enough building data to answer that accurately. You can ask me for room locations, route steps, nearest facilities, or accessibility options.",
            suggestedVoiceResponse = "I don't have enough building data to answer that accurately.",
            action = AIAssistantAction.NONE,
            confidence = 0.5f
        )
    }

    /**
     * Authoritative nearest node calculation using actual (x, y, floor) coordinates.
     */
    private fun findNearestNode(
        building: Building,
        context: AINavigationContext,
        filter: (NavNode) -> Boolean
    ): Pair<NavNode?, Float> {
        val candidates = building.nodes.filter(filter)
        if (candidates.isEmpty()) return Pair(null, 0f)

        val userX = context.currentX ?: 250f
        val userY = context.currentY ?: 250f
        val userFloor = context.currentFloor

        val sorted = candidates.map { node ->
            val dx = node.x - userX
            val dy = node.y - userY
            val floorDiff = abs(node.floor - userFloor)
            // Weight floor changes by 150m penalty to strongly prefer same-floor facilities
            val dist = sqrt(dx * dx + dy * dy) + (floorDiff * 150f)
            node to dist
        }.sortedBy { it.second }

        return sorted.firstOrNull() ?: Pair(null, 0f)
    }

    /**
     * Deterministic search over authoritative building node data.
     */
    private fun findMatchingNodes(building: Building, query: String): List<NavNode> {
        val q = query.lowercase().trim()
        val cleanTerms = q
            .replace("where is", "")
            .replace("which floor is", "")
            .replace("what floor is", "")
            .replace("how do i get to", "")
            .replace("take me to", "")
            .replace("navigate to", "")
            .replace("find", "")
            .replace("the", "")
            .trim()
            .split(" ", "-", ",")
            .filter { it.length >= 2 }

        val scored = building.nodes.map { node ->
            var score = 0
            val nameLow = node.name.lowercase()
            val codeLow = node.code.lowercase()
            val descLow = node.description.lowercase()

            if (q.contains(nameLow) || nameLow.contains(q)) score += 100
            if (q.contains(codeLow) || codeLow.contains(q)) score += 90

            for (term in cleanTerms) {
                if (nameLow.contains(term)) score += 40
                if (codeLow.contains(term)) score += 50
                if (node.keywords.any { it.lowercase().contains(term) }) score += 45
                if (descLow.contains(term)) score += 15
            }

            // Semantic mappings
            if (q.contains("ai") || q.contains("lab") || q.contains("cs")) {
                if (node.id.contains("cslab") || node.name.contains("AI", ignoreCase = true)) score += 60
            }
            if (q.contains("library") || q.contains("book") || q.contains("study")) {
                if (node.category == NodeCategory.LIBRARY || node.id.contains("library")) score += 60
            }

            node to score
        }.filter { it.second > 30 }.sortedByDescending { it.second }

        return scored.map { it.first }
    }

    private fun parseLandmarkJson(jsonStr: String, building: Building): AILandmarkResult? {
        return try {
            val clean = jsonStr.replace("```json", "").replace("```", "").trim()
            val obj = JSONObject(clean)
            val matchedId = obj.optString("matchedNodeId", "")
            val landmarkName = obj.optString("landmarkName", "Indoor Landmark")
            val confidence = obj.optDouble("confidence", 0.88).toFloat()
            val explanation = obj.optString("explanation", "Recognized visual landmark.")

            val node = building.nodes.firstOrNull { it.id == matchedId }
            if (node != null) {
                AILandmarkResult(node.id, landmarkName, confidence, explanation)
            } else {
                AILandmarkResult(null, landmarkName, 0.4f, "No exact match found.")
            }
        } catch (e: Exception) {
            null
        }
    }

    private fun localFallbackLandmarkMatch(building: Building): AILandmarkResult {
        val sample = building.presetLandmarks.firstOrNull()
        if (sample != null) {
            return AILandmarkResult(
                matchedNodeId = sample.nodeId,
                landmarkName = sample.expectedText,
                confidence = 0.94f,
                explanation = "Visual landmark detected: \"${sample.expectedText}\"."
            )
        }
        val firstNode = building.nodes.firstOrNull()
        return AILandmarkResult(
            matchedNodeId = firstNode?.id,
            landmarkName = firstNode?.visualSignageHint ?: "Main Corridor Sign",
            confidence = 0.85f,
            explanation = "Calibrated indoor anchor position."
        )
    }

    private fun bitmapToBase64(bitmap: Bitmap): String {
        val outputStream = ByteArrayOutputStream()
        bitmap.compress(Bitmap.CompressFormat.JPEG, 85, outputStream)
        val byteArray = outputStream.toByteArray()
        return Base64.encodeToString(byteArray, Base64.NO_WRAP)
    }
}
